routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UsersController@calcEfficiency')->name('dashboard');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/index', function () {
    return view('index');
});

Route::resource('users', 'UsersController');
Route::resource('teams', 'TeamsController');
Route::get('/tasks', 'TasksController@index')->name('tasks.index');
Route::get('/tasks/resolved', 'TasksController@resolvedTasks')->name('tasks.resolved');
Route::get('/tasks/unresolved', 'TasksController@unresolvedTasks')->name('tasks.unresolved');
Route::get('/tasks/assigned', 'TasksController@assignedTasks')->name('tasks.assigned');

Route::get('/tasks/create', 'TasksController@create')->name('tasks.create');
Route::post('/tasks', 'TasksController@store')->name('tasks.store');
Route::get('tasks/{task}/edit', 'TasksController@edit')->name('tasks.edit');
Route::put('/tasks/{task}', 'TasksController@update')->name('tasks.update');
Route::put('/tasks/{task}/{member}/resolve', 'TasksController@resolve')->name('tasks.resolve');
Route::put('/tasks/{task}/{member}/unresolve', 'TasksController@unresolve')->name('tasks.unresolve');
Route::put('/tasks/{task}/approve', 'TasksController@approve')->name('tasks.approve');
Route::put('/tasks/{task}/reject', 'TasksController@reject')->name('tasks.reject');
Route::get('/tasks/{task}', 'TasksController@show')->name('tasks.show');
Route::get('/users/{user}', 'UsersController@show')->name('users.show');
Route::get('/members', 'UsersController@members')->name('members');
Route::get('/notifications', 'NotificationsController@index')->name('notifications')->middleware('auth');
Route::put('/tasks/{task}/reassign', 'TasksController@reassign')->name('tasks.reassign');
Route::get('/tasks/{task}/assign', 'TasksController@edit')->name('tasks.assign');
Route::put('/tasks/{task}/assign', 'TasksController@reassign')->name('tasks.assignManually');

resources/views/includes/footer.blade.php
<footer class="py-4 bg-light mt-4">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2020</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

resources/views/includes/message.blade.php
<div class="row">
    <div class="col-md-12">
        @if (session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session()->get('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        @endif
        @if (session()->has('warning'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ session()->get('warning') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        @endif
        @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session()->get('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        @endif
    </div>
</div>

resources/views/includes/navbar.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ route('dashboard') }}">Task Manager</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    @if (auth()->user()->unreadNotifications->count())
        <div class="notifications">
            <a href="{{ route('notifications') }}"><i class="fas fa-bell"></i>
                <sup>{{ auth()->user()->unreadNotifications->count() }}</sup></a>
        </div>
    @endif
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <form action="{{ route('logout') }}" method="post">
                    @csrf
                    <button class="dropdown-item">Logout</button>
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/includes/sidebar.blade.php
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link{{ Request::is('dashboard') ? 'active' : '' }}" href="{{ route('dashboard') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">Interface</div>
                @if (auth()->user()->isAdmin())
                    <a class="nav-link {{ Request::is('users') ? 'active' : '' }} {{ Request::is('users*') ? '' : 'collapsed' }}" href="{{ route('users.index') }}" data-target="#collapseUsers" data-toggle="collapse" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                        Users
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse {{ Request::is('users*') ? 'show' : '' }}" id="collapseUsers" aria-labelledby="headingOne">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link {{ Request::is('users/create') ? 'active' : '' }}" href="{{ route('users.create') }}">Create User</a>
                            <a class="nav-link {{ Request::is('users') ? 'active' : '' }} " href="{{ route('users.index') }}">View Users</a>
                        </nav>
                    </div>
                    <a class="nav-link {{ Request::is('teams*') ? '' : 'collapsed'  }} {{ Request::is('teams*') ? 'active' : ''  }} " href="#" data-target="#collapseTeams" data-toggle="collapse">
                        <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                        Teams
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse {{ Request::is('teams*') ? 'show' : '' }}" id="collapseTeams" aria-labelledby="headingOne">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link {{ Request::is('teams/create') ? 'active' : '' }}" href="{{ route('teams.create') }}">Create Team</a>
                            <a class="nav-link {{ Request::is('teams') ? 'active' : '' }} " href="{{ route('teams.index') }}">View Teams</a>
                        </nav>
                    </div>
                @endif

                @if (auth()->user()->isLeader())
                    <a class="nav-link {{ Request::is('members') ? 'active' : '' }}" href="{{ route('members',auth()->user()->team->name) }}" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                        Members
                    </a>
                @endif


                <a class="nav-link  {{ Request::is('*tasks*') ? '' : 'collapsed'  }} {{ Request::is('*tasks*') ? 'active' : '' }}" href="{{ (!auth()->user()->isLeader()) ? route('tasks.index') : '#' }}" {{ (!auth()->user()->isLeader()) ? '' : "data-toggle=collapse" }} data-target="#collapseTasks" aria-expanded="false" aria-controls="collapseTasks">
                    <div class="sb-nav-link-icon"><i class="fas fa-tasks"></i></div>
                    Tasks
                    @if (auth()->user()->isLeader())
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    @endif
                </a>
                @if (auth()->user()->isLeader())
                    <div class="collapse {{ Request::is('*tasks*') ? 'show' : '' }}" id="collapseTasks" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link  {{ Request::is('tasks.create') ? 'active' : '' }}" href="{{ route('tasks.create',auth()->user()->team->name) }}">Create Task</a>
                            <a class="nav-link  {{ Request::is('tasks.index') ? 'active' : '' }}" href="{{route('tasks.index')}}">View Tasks</a>
                        </nav>
                    </div>
                @endif

        </div>
    </nav>
</div>